### ISSUE TITLE
Posts are fetched again when you come back

### ISSUE THREAD

**Issue by abayken** [akashGitAgni/Recyclerview-MVVM-Retrofit#2]
Hey! I liked your implementation, but I noticed something which seems incorrect. When you go back from comments fragment to posts fragment, the list of posts are fetched again from API. I think it is bad practice. The reason for this is simple: Your fragment is recreated and it calls `refreshPosts` method again. I think `Fragment` should only observe for changes, it should not call methods like `refreshPosts`. How you would solve above problem?

**Comment by akashGitAgni** [comment]
Ya you are right. I would just refresh post in ViewModel and let Fragment observer the changes. I would also give user to swipe down and refresh the posts.
